CREATE TABLE `Locations` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(100) COLLATE UTF8_UNICODE_CI NOT NULL,
    `state_id` CHAR(2) COLLATE UTF8_UNICODE_CI NOT NULL,
    `state_name` VARCHAR(45) COLLATE UTF8_UNICODE_CI NOT NULL,
    `lat` DECIMAL(11,7) NOT NULL,
    `lng` DECIMAL(11,7) NOT NULL,
    `population` BIGINT(20) DEFAULT NULL,
    `ranking` INT(11) DEFAULT NULL,
    `county_name` VARCHAR(150) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `id` (`id`),
    FULLTEXT KEY `fts_locations` (`city`,`state_id`,`state_name`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;
