CREATE TABLE Payout_Accounts (
    id CHAR(36) NOT NULL UNIQUE,
    user_id INT UNSIGNED NOT NULL,
    account_id CHAR(25) NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed BOOL NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE CASCADE
);