CREATE TABLE `Products` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(250) COLLATE UTF8_UNICODE_CI NOT NULL,
  `description` TEXT COLLATE UTF8_UNICODE_CI,
  `product_categories_sub_id` INT(10) UNSIGNED NOT NULL,
  `location_id` INT(10) UNSIGNED NOT NULL,
  `dropoff_distance` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '20',
  `price_full` DECIMAL(10,2) UNSIGNED NOT NULL,
  `price_half` DECIMAL(10,2) UNSIGNED NOT NULL,
  `image` CHAR(41) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
  `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `user_id` (`user_id`),
  KEY `product_categories_sub_id` (`product_categories_sub_id`),
  KEY `location_id` (`location_id`),
  CONSTRAINT `Products_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `Products_ibfk_2` FOREIGN KEY (`product_categories_sub_id`) REFERENCES `Product_Categories_Sub` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `Products_ibfk_3` FOREIGN KEY (`location_id`) REFERENCES `Locations` (`id`) ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;
